en = {
    '安东': 'Andong',
    '安徽': 'Anhui',
    '察哈尔': 'Chahar',
    '福建': 'Fujian',
    '甘肃': 'Gansu',
    '广东': 'Guangdong',
    '广西': 'Guangxi',
    '贵州': 'Guizhou',
    '海南': 'Hainan',
    '河北': 'Hebei',
    '合江': 'Hejiang',
    '黑龙江': 'Heilongjiang',
    '河南': 'Henan',
    '湖北': 'Hubei',
    '湖南': 'Hunan',
    '江苏': 'Jiangsu',
    '江西': 'Jiangxi',
    '吉林': 'Jilin',
    '辽北': 'Liaobei',
    '辽东': 'Liaodong',
    '辽宁': 'Liaoning',
    '辽西': 'Liaoxi',
    '嫩江': 'Nenjiang',
    '宁夏': 'Ningxia',
    '牡丹江': 'Mudanjiang',
    '平原': 'Pingyuan',
    '青海': 'Qinghai',
    '热河': 'Rehe',
    '四川': 'Sichuan',
    '陕西': 'Shaanxi',
    '山东': 'Shandong',
    '山西': 'Shanxi',
    '松江': 'Songjiang',
    '绥远': 'Suiyuan',
    '台湾': 'Taiwan',
    '西康': 'Xikang',
    '兴安': "Xing'an",
    '新疆': 'Xinjiang',
    '云南': 'Yunnan',
    '浙江': 'Zhejiang',

    '广西': 'Guangxi',
    '内蒙古': 'Inner Mongolia',
    '宁夏': 'Ningxia',
    '西藏': 'Tibet',
    '新疆': 'Xinjiang',

    '鞍山': 'Anshan',
    '北京': 'Beijing',
    '本溪': 'Benxi',
    '长春': 'Changchun',
    '重庆': 'Chongqing',
    '大连': 'Dalian',
    '旅大': 'Lüda',
    '抚顺': 'Fushun',
    '广州': 'Guangzhou',
    '哈尔滨': 'Harbin',
    '南京': 'Nanjing',
    '上海': 'Shanghai',
    '沈阳': 'Shenyang',
    '天津': 'Tianjin',
    '汉口': 'Hankou',
    '武汉': 'Wuhan',
    '西安': "Xi'an",

    '香港': 'Hong Kong',
    '澳门': 'Macau',

    '서울': 'Seoul',
    '부산': 'Busan',
    '대구': 'Daegu',
    '인천': 'Incheon',
    '광주': 'Gwangju',
    '대전': 'Daejeon',
    '울산': 'Ulsan',
    '세종': 'Sejong',
    '경기': 'Gyeonggi',
    '강원': 'Gangwon',
    '충북': 'Chungbuk',
    '충남': 'Chungnam',
    '전북': 'Jeonbuk',
    '전남': 'Jeonnam',
    '경북': 'Gyeongbuk',
    '경남': 'Gyeongnam',
    '제주': 'Jeju',
    '검역': 'Quarantine',
}

us_states = {
    'AL': 'Alabama',
    'AK': 'Alaska',
    'AZ': 'Arizona',
    'AR': 'Arkansas',
    'CA': 'California',
    'CO': 'Colorado',
    'CT': 'Connecticut',
    'DE': 'Delaware',
    'FL': 'Florida',
    'GA': 'Georgia',
    'HI': 'Hawaii',
    'ID': 'Idaho',
    'IL': 'Illinois',
    'IN': 'Indiana',
    'IA': 'Iowa',
    'KS': 'Kansas',
    'KY': 'Kentucky',
    'LA': 'Louisiana',
    'ME': 'Maine',
    'MD': 'Maryland',
    'MA': 'Massachusetts',
    'MI': 'Michigan',
    'MN': 'Minnesota',
    'MS': 'Mississippi',
    'MO': 'Missouri',
    'MT': 'Montana',
    'NE': 'Nebraska',
    'NV': 'Nevada',
    'NH': 'New Hampshire',
    'NJ': 'New Jersey',
    'NM': 'New Mexico',
    'NY': 'New York',
    'NC': 'North Carolina',
    'ND': 'North Dakota',
    'OH': 'Ohio',
    'OK': 'Oklahoma',
    'OR': 'Oregon',
    'PA': 'Pennsylvania',
    'RI': 'Rhode Island',
    'SC': 'South Carolina',
    'SD': 'South Dakota',
    'TN': 'Tennessee',
    'TX': 'Texas',
    'UT': 'Utah',
    'VT': 'Vermont',
    'VA': 'Virginia',
    'WA': 'Washington',
    'WV': 'West Virginia',
    'WI': 'Wisconsin',
    'WY': 'Wyoming',

    'AS': 'American Samoa',
    'DC': 'District of Columbia',
    'FM': 'Federated States of Micronesia',
    'GU': 'Guam',
    'MH': 'Marshall Islands',
    'MP': 'Northern Mariana Islands',
    'PW': 'Palau',
    'PR': 'Puerto Rico',
    'VI': 'Virgin Islands',
}

ll_csv2csv = {
    # Gansu, China
    '37.8099,101.0583': '36.0611,103.8343',
    # Hebei, China
    '39.549,116.1306': '38.0428,114.5149',
    # District of Columbia
    '38.8974,-77.0268': '38.9072,-77.0369',
}

ll_rest2csv = {
    # United Arab Emirates
    '23.4241,53.8478': '24.0,54.0',
    # Thailand
    '15.87,100.9925': '15.0,101.0',
    # Philippines
    '12.8797,121.774': '13.0,122.0',
    # Croatia
    '45.1667,15.5': '45.1,15.2',
    # Mexico
    '23.0,-102.0': '23.6345,-102.5528',
    # Luxembourg
    '49.8144,6.1317;': '49.8153,6.1296',
    # Tunisia
    '33.8869,9.5375': '34.0,9.0',
    # Cambodia
    '12.5657,104.991': '11.55,104.9167',
    # Sri Lanka
    '7.8731,80.7718': '7.0,81.0',
    # Nepal
    '28.3949,84.124': '28.1667,84.25',
    # Luxembourg
    '49.8144,6.1317': '49.8153,6.1296',
    # Romania
    '46.0,25.0': '45.9432,24.9668',
    # British Columbia, Canada
    '53.7267,-127.6476': '49.2827,-123.1207',
    # Gansu, China
    '37.8099,101.0583': '36.0611,103.8343',
    # Hebei, China
    '39.549,116.1306': '38.0428,114.5149',
    # District of Columbia
    '38.8974,-77.0268': '38.9072,-77.0369',
    # Cuba
    '21.5218,-77.7812': '22.0,-80.0',
    # French Guiana
    '4.0,-53.0': '3.9339,-53.1258',
}

co_names = {
    'Republic of Korea': 'South Korea',
    'Korea, South': 'South Korea',
    'Iran (Islamic Republic of)': 'Iran',
    'Republic of Moldova': 'Moldova',
    'Taiwan*': 'Taiwan',
}
