en = {
        '安东': 'Andong',
        '安徽': 'Anhui',
        '察哈尔': 'Chahar',
        '福建': 'Fujian',
        '甘肃': 'Gansu',
        '广东': 'Guangdong',
        '广西': 'Guangxi',
        '贵州': 'Guizhou',
        '海南': 'Hainan',
        '河北': 'Hebei',
        '合江': 'Hejiang',
        '黑龙江': 'Heilongjiang',
        '河南': 'Henan',
        '湖北': 'Hubei',
        '湖南': 'Hunan',
        '江苏': 'Jiangsu',
        '江西': 'Jiangxi',
        '吉林': 'Jilin',
        '辽北': 'Liaobei',
        '辽东': 'Liaodong',
        '辽宁': 'Liaoning',
        '辽西': 'Liaoxi',
        '嫩江': 'Nenjiang',
        '宁夏': 'Ningxia',
        '牡丹江': 'Mudanjiang',
        '平原': 'Pingyuan',
        '青海': 'Qinghai',
        '热河': 'Rehe',
        '四川': 'Sichuan',
        '陕西': 'Shaanxi',
        '山东': 'Shandong',
        '山西': 'Shanxi',
        '松江': 'Songjiang',
        '绥远': 'Suiyuan',
        '台湾': 'Taiwan',
        '西康': 'Xikang',
        '兴安': "Xing'an",
        '新疆': 'Xinjiang',
        '云南': 'Yunnan',
        '浙江': 'Zhejiang',

        '广西': 'Guangxi',
        '内蒙古': 'Inner Mongolia',
        '宁夏': 'Ningxia',
        '西藏': 'Tibet',
        '新疆': 'Xinjiang',

        '鞍山': 'Anshan',
        '北京': 'Beijing',
        '本溪': 'Benxi',
        '长春': 'Changchun',
        '重庆': 'Chongqing',
        '大连': 'Dalian',
        '旅大': 'Lüda',
        '抚顺': 'Fushun',
        '广州': 'Guangzhou',
        '哈尔滨': 'Harbin',
        '南京': 'Nanjing',
        '上海': 'Shanghai',
        '沈阳': 'Shenyang',
        '天津': 'Tianjin',
        '汉口': 'Hankou',
        '武汉': 'Wuhan',
        '西安': "Xi'an",

        '香港': 'Hong Kong',
        '澳门': 'Macau',
}
